/*
 * File: app/store/Searches.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Feed.store.Searches', {
    extend: 'Ext.data.Store',
    alias: 'store.search',

    requires: [
        'Feed.model.Search'
    ],

    config: {
        model: 'Feed.model.Search',
        storeId: 'Searches',
        proxy: {
            type: 'jsonp',
            url: 'https://ajax.googleapis.com/ajax/services/feed/find?v=1.0',
            reader: {
                type: 'json',
                rootProperty: 'responseData.entries'
            }
        }
    },

    search: function(keywords) {
        this.load({
            params:{
                q: keywords
            }
        });

    }

});