/*
 * File: app/model/Search.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Feed.model.Search', {
    extend: 'Ext.data.Model',
    alias: 'model.search',

    config: {
        fields: [
            {
                name: 'title'
            },
            {
                name: 'url'
            },
            {
                name: 'description',
                mapping: 'contentSnippet'
            }
        ]
    }
});